### ISSUE TITLE
Completar modelo de kanjis con propuesta.

### ISSUE THREAD

**Issue by frmadem** [eoi-japones/tools#7]
# Motivación

Se necesitan estructuras de datos adicionales para poder agregar de manera supervisada y revisable información a los kanjis. 

## Historias alternativas

**Descripción**:  un kanji puede tener una historia alternativa (a la que se da en clase) y se puede almacenar en el sistema. 
Su estructura sería la siguiente:

```yaml
id: <identificador del kanji o compuesto>
de: <persona que ha pensado la historia o ANÓNIMO>
historia: <historia del kanji (puede ser multilínea)>
```
